// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCINRuerToLYoumEM7PBN-79oJNQs4twAk',
    appId: '1:586710635386:web:b827b27c445987d9453cc3',
    messagingSenderId: '586710635386',
    projectId: 'gmrtest-5241f',
    authDomain: 'gmrtest-5241f.firebaseapp.com',
    storageBucket: 'gmrtest-5241f.appspot.com',
    measurementId: 'G-MDDRCL13QR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD-kCwj527NkO3jDPcB4BNvbx5JTw_S94',
    appId: '1:586710635386:android:579eedf175bf284b453cc3',
    messagingSenderId: '586710635386',
    projectId: 'gmrtest-5241f',
    storageBucket: 'gmrtest-5241f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV5ovJ4mr6KXPGbRmJl6ALl3BIsPUpnVw',
    appId: '1:586710635386:ios:be2db03fe03fa521453cc3',
    messagingSenderId: '586710635386',
    projectId: 'gmrtest-5241f',
    storageBucket: 'gmrtest-5241f.appspot.com',
    iosBundleId: 'com.example.gmrTestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV5ovJ4mr6KXPGbRmJl6ALl3BIsPUpnVw',
    appId: '1:586710635386:ios:607343da14bfe292453cc3',
    messagingSenderId: '586710635386',
    projectId: 'gmrtest-5241f',
    storageBucket: 'gmrtest-5241f.appspot.com',
    iosBundleId: 'com.example.gmrTestApp.RunnerTests',
  );
}
